const domains={D1:'Domain 1: Cloud Concepts',D2:'Domain 2: Security and Compliance',D3:'Domain 3: Cloud Technology and Services',D4:'Domain 4: Billing, Pricing, and Support'};
const raw=[
['D1.1.1','Cloud Computing','What is cloud computing?','Cloud computing means renting technology resources such as <strong>servers</strong>, <strong>storage</strong>, <strong>databases</strong>, and <strong>software</strong> over the internet instead of buying and running them yourself.','Like using electricity from the power grid instead of building your own power plant.','','Avoid buying hardware or pay only for what you use = cloud computing.'],
['D1.1.2','IaaS','What is Infrastructure as a Service?','<strong>IaaS</strong> provides basic infrastructure such as virtual servers, storage, and networking while you manage the operating system, applications, and data. <strong>Amazon EC2</strong> is the classic example.','','','If you manage the operating system, think IaaS.'],
['D1.1.3','PaaS','What is Platform as a Service?','<strong>PaaS</strong> gives developers a managed platform for running applications without managing much of the underlying infrastructure. <strong>Elastic Beanstalk</strong> is a common AWS example.','','','Upload code and let AWS set up the environment = PaaS-style.'],
['D1.1.4','SaaS','What is Software as a Service?','<strong>SaaS</strong> is a complete application delivered over the internet where the provider manages the infrastructure, platform, and application.','Like eating at a restaurant: you consume the finished meal.','','If the customer only uses the app, it is SaaS.'],
['D1.2.1','Six Cloud Advantages','What are the six AWS advantages of cloud computing?','They are <strong>trade fixed expense for variable expense</strong>, <strong>benefit from massive economies of scale</strong>, <strong>stop guessing capacity</strong>, <strong>increase speed and agility</strong>, <strong>stop spending money running and maintaining data centers</strong>, and <strong>go global in minutes</strong>.','','','Memorize these almost verbatim.'],
['D1.3.1','CapEx vs OpEx','How are CapEx and OpEx different?','<strong>CapEx</strong> is large upfront spending on assets such as servers. <strong>OpEx</strong> is ongoing spending for services as they are used. AWS commonly shifts spend toward OpEx.','','Purchase price alone is not total cost.','Avoid upfront investment = fixed to variable.'],
['D1.4.1','Well-Architected Pillars','What are the six Well-Architected pillars?','The six pillars are <strong>Operational Excellence</strong>, <strong>Security</strong>, <strong>Reliability</strong>, <strong>Performance Efficiency</strong>, <strong>Cost Optimization</strong>, and <strong>Sustainability</strong>.','','Sustainability is easy to forget.','Architecture best practices = Well-Architected.'],
['D1.5.1','AWS CAF','What is the AWS Cloud Adoption Framework?','<strong>AWS CAF</strong> helps organizations plan cloud adoption across business, people, governance, platform, security, and operations.','','CAF is a framework, not a service to configure.','Organizational cloud adoption = AWS CAF.'],
['D1.6.1','Elasticity','What is elasticity?','<strong>Elasticity</strong> is the ability to automatically add or remove resources as demand changes.','Opening more checkout lanes during a rush.','','Elasticity includes scaling down.'],
['D1.6.2','Horizontal vs Vertical Scaling','How are horizontal and vertical scaling different?','<strong>Horizontal scaling</strong> adds more resources, such as more EC2 instances. <strong>Vertical scaling</strong> makes one resource bigger, such as a larger EC2 instance.','','','Scale out = horizontal. Scale up = vertical.'],
['D2.1.1','Shared Responsibility Model','What is the AWS Shared Responsibility Model?','The <strong>Shared Responsibility Model</strong> divides security duties between AWS and the customer. AWS handles <strong>security of the cloud</strong>; the customer handles <strong>security in the cloud</strong>.','','','One of the most tested ideas.'],
['D2.1.2','EC2 Patching','Who patches the guest operating system on EC2?','The <strong>customer</strong> patches the guest operating system on <strong>Amazon EC2</strong>. AWS patches the underlying physical host infrastructure.','','This is a classic exam trap.','EC2 database = customer patches OS; RDS database = AWS handles OS.'],
['D2.1.3','RDS Patching','Who patches the operating system for Amazon RDS?','<strong>AWS</strong> handles the underlying operating system and database platform maintenance for <strong>Amazon RDS</strong> because RDS is managed.','','','Managed service = AWS handles more infrastructure work.'],
['D2.2.1','IAM','What is IAM?','<strong>AWS Identity and Access Management</strong> controls who can access AWS resources and what actions they can perform.','','','Who can do what = IAM.'],
['D2.2.2','Root User','What is the AWS account root user?','The <strong>root user</strong> is the original account identity with full access to everything in the AWS account. Protect it with MFA and avoid daily use.','','Do not use root for everyday work.','Secure root, then avoid root.'],
['D2.2.3','IAM Role','What is an IAM role?','An <strong>IAM role</strong> is an identity with permissions that can be temporarily assumed by trusted users, AWS services, or applications.','','','EC2 needs S3 access? Use a role, not hard-coded keys.'],
['D2.2.4','Policy Evaluation','How does IAM evaluate allow and deny permissions?','Requests are <strong>implicitly denied</strong> by default. An explicit <strong>Allow</strong> grants access, but any explicit <strong>Deny</strong> overrides allows.','','','Explicit Deny wins.'],
['D2.3.1','AWS Organizations','What is AWS Organizations?','<strong>AWS Organizations</strong> centrally manages multiple AWS accounts and supports consolidated billing, OUs, SCPs, and multi-account governance.','','','Manage many AWS accounts centrally = Organizations.'],
['D2.3.2','SCP','What is a Service Control Policy?','A <strong>Service Control Policy</strong>, or <strong>SCP</strong>, sets maximum permissions for accounts or OUs. SCPs do not grant permissions by themselves.','','SCPs are guardrails, not permission grants.','Account-level guardrail = SCP.'],
['D2.4.1','KMS','What is AWS KMS?','<strong>AWS Key Management Service</strong> creates and manages cryptographic keys used by AWS services and applications.','','','Managed encryption keys = KMS.'],
['D2.4.2','Secrets Manager','What is AWS Secrets Manager used for?','<strong>AWS Secrets Manager</strong> stores, encrypts, retrieves, and can rotate secrets such as database passwords and API keys.','','','Automatic secret rotation = Secrets Manager.'],
['D2.5.1','GuardDuty','What is Amazon GuardDuty?','<strong>Amazon GuardDuty</strong> is a threat detection service that analyzes activity signals to find suspicious behavior.','','','Suspicious activity or threat detection = GuardDuty.'],
['D2.5.2','Macie','What is Amazon Macie?','<strong>Amazon Macie</strong> discovers and helps protect sensitive data in Amazon S3.','','','Sensitive data in S3 = Macie.'],
['D2.5.3','CloudTrail','What is AWS CloudTrail?','<strong>AWS CloudTrail</strong> records AWS API activity, such as who created, changed, deleted, or accessed resources.','','','Who did what = CloudTrail.'],
['D2.5.4','Config','What is AWS Config?','<strong>AWS Config</strong> records resource configurations over time and evaluates them against rules.','','','What changed and is it compliant = Config.'],
['D2.6.1','WAF vs Shield','How are AWS WAF and AWS Shield different?','<strong>AWS WAF</strong> filters web application requests. <strong>AWS Shield</strong> protects against DDoS attacks.','','','Web request rules = WAF. DDoS = Shield.'],
['D2.7.1','AWS Artifact','What is AWS Artifact?','<strong>AWS Artifact</strong> provides access to AWS compliance reports and certain agreements.','','','Download AWS compliance reports = Artifact.'],
['D2.8.1','Cognito','What is Amazon Cognito?','<strong>Amazon Cognito</strong> provides authentication and authorization features for application users, such as sign-up and sign-in.','','','App user login = Cognito.'],
['D3.1.1','Region','What is an AWS Region?','An <strong>AWS Region</strong> is a physical geographic area containing multiple Availability Zones.','','','Choose Region for latency, compliance, cost, and service availability.'],
['D3.1.2','Availability Zone','What is an Availability Zone?','An <strong>Availability Zone</strong> is one or more discrete data centers inside a Region, designed for isolation and low-latency connectivity.','','','Multi-AZ = higher availability inside a Region.'],
['D3.1.3','CloudFront Edge','What is an edge location?','An <strong>edge location</strong> is a site used by CloudFront and related services to cache content closer to users.','','','Content caching near users = edge locations.'],
['D3.2.1','EC2','What is Amazon EC2?','<strong>Amazon EC2</strong> provides resizable virtual servers in AWS.','','','Virtual server = EC2.'],
['D3.2.2','On-Demand','When should you use EC2 On-Demand Instances?','Use <strong>On-Demand Instances</strong> for flexible, short-term, unpredictable workloads with no long-term commitment.','','','Unknown usage, no commitment = On-Demand.'],
['D3.2.3','Reserved Instances','When should you use Reserved Instances?','Use <strong>Reserved Instances</strong> for predictable workloads where you can commit to a 1-year or 3-year term for a discount.','','','Steady predictable EC2 usage = RI or Savings Plan.'],
['D3.2.4','Spot Instances','When should you use Spot Instances?','Use <strong>Spot Instances</strong> for fault-tolerant workloads that can handle interruption, such as batch jobs and test environments.','','Do not choose Spot for workloads that cannot be interrupted.','Interruptible = Spot.'],
['D3.3.1','Lambda','What is AWS Lambda?','<strong>AWS Lambda</strong> runs code without you managing servers. You pay for requests and compute time while the function runs.','','','Event-driven code with no servers = Lambda.'],
['D3.3.2','Fargate','What is AWS Fargate?','<strong>AWS Fargate</strong> is serverless compute for containers, letting you run containers without managing EC2 instances.','','','Containers without managing servers = Fargate.'],
['D3.3.3','ECS vs EKS','How are ECS and EKS different?','<strong>Amazon ECS</strong> is AWS-native container orchestration. <strong>Amazon EKS</strong> is managed Kubernetes on AWS.','','','AWS-native containers = ECS. Managed Kubernetes = EKS.'],
['D3.4.1','Load Balancer','What does a load balancer do?','A <strong>load balancer</strong> distributes incoming traffic across multiple targets such as EC2 instances or containers.','Like a host seating customers across open restaurant sections.','',''],
['D3.4.2','ALB vs NLB','How are ALB and NLB different?','Use an <strong>Application Load Balancer</strong> for HTTP/HTTPS routing. Use a <strong>Network Load Balancer</strong> for high-performance TCP, UDP, or TLS traffic.','','','HTTP/HTTPS = ALB. TCP/UDP = NLB.'],
['D3.5.1','S3','What is Amazon S3?','<strong>Amazon S3</strong> is object storage for files, backups, logs, static websites, media, and data lakes.','','','Object storage = S3.'],
['D3.5.2','S3 Durability','What durability is S3 designed for?','<strong>Amazon S3</strong> is designed for <strong>99.999999999% durability</strong>, often called eleven 9s.','','Eleven 9s means durability, not availability.','Memorize this number.'],
['D3.5.3','EBS vs EFS','How are EBS and EFS different?','<strong>Amazon EBS</strong> is block storage for EC2, like a virtual hard drive. <strong>Amazon EFS</strong> is shared Linux file storage that multiple instances can mount.','','','Block = EBS. Shared Linux file system = EFS.'],
['D3.6.1','RDS','What is Amazon RDS?','<strong>Amazon RDS</strong> is a managed relational database service for engines such as MySQL, PostgreSQL, MariaDB, Oracle, SQL Server, and Db2.','','','Managed relational database = RDS.'],
['D3.6.2','Multi-AZ vs Read Replica','How are RDS Multi-AZ and Read Replicas different?','<strong>RDS Multi-AZ</strong> is for high availability and failover. <strong>Read Replicas</strong> are for read scaling.','','This is one of the biggest database traps.','Failover = Multi-AZ. Read scaling = Read Replica.'],
['D3.6.3','DynamoDB','What is Amazon DynamoDB?','<strong>Amazon DynamoDB</strong> is a fully managed NoSQL key-value and document database for high-scale, low-latency applications.','','','Serverless NoSQL = DynamoDB.'],
['D3.6.4','Redshift','What is Amazon Redshift?','<strong>Amazon Redshift</strong> is a cloud data warehouse used for large-scale analytics and business intelligence queries.','','','Data warehouse = Redshift.'],
['D3.7.1','VPC','What is Amazon VPC?','<strong>Amazon VPC</strong> is a logically isolated virtual network in AWS where you launch resources.','','','Private network in AWS = VPC.'],
['D3.7.2','Security Group vs NACL','How are Security Groups and NACLs different?','A <strong>security group</strong> is stateful and resource-level with allow rules. A <strong>NACL</strong> is stateless and subnet-level with allow and deny rules.','','Classic exam trap.','Instance-level stateful = SG. Subnet-level stateless = NACL.'],
['D3.7.3','NAT Gateway','What is a NAT Gateway used for?','A <strong>NAT Gateway</strong> lets private subnet resources initiate outbound internet access while blocking unsolicited inbound internet connections.','','','Private subnet needs outbound updates = NAT Gateway.'],
['D3.7.4','Route 53','What is Amazon Route 53?','<strong>Amazon Route 53</strong> is AWS DNS service for routing users to applications and resources.','','','DNS = Route 53.'],
['D3.8.1','SQS vs SNS','How are SQS and SNS different?','<strong>Amazon SQS</strong> is a queue for decoupling and buffering. <strong>Amazon SNS</strong> is pub/sub messaging for fan-out notifications.','','','Queue = SQS. Fan-out = SNS.'],
['D3.8.2','Step Functions','What is AWS Step Functions?','<strong>AWS Step Functions</strong> coordinates multi-step workflows across AWS services using state machines.','','','Workflow orchestration = Step Functions.'],
['D3.9.1','Athena','What is Amazon Athena?','<strong>Amazon Athena</strong> lets you query data in S3 using SQL without managing servers.','','','SQL on S3 = Athena.'],
['D3.9.2','Glue','What is AWS Glue?','<strong>AWS Glue</strong> is a serverless data integration service for ETL jobs and data cataloging.','','','ETL and data catalog = Glue.'],
['D3.9.3','Kinesis','What is Amazon Kinesis?','<strong>Amazon Kinesis</strong> collects, processes, and analyzes streaming data in near real time.','','','Real-time streaming data = Kinesis.'],
['D3.10.1','Machine Learning Services','How do common AWS AI services map to tasks?','<strong>Rekognition</strong> analyzes images/video, <strong>Comprehend</strong> analyzes text, <strong>Polly</strong> turns text to speech, <strong>Transcribe</strong> turns speech to text, and <strong>Translate</strong> translates text.','','','Learn the keyword-to-service mapping.'],
['D3.11.1','CloudFormation','What is AWS CloudFormation?','<strong>AWS CloudFormation</strong> provisions AWS infrastructure from templates, enabling repeatable infrastructure as code.','','','AWS infrastructure as code templates = CloudFormation.'],
['D3.12.1','CloudWatch','What is Amazon CloudWatch?','<strong>Amazon CloudWatch</strong> collects metrics, logs, alarms, and dashboards for monitoring AWS resources and applications.','','','Metrics, logs, alarms = CloudWatch.'],
['D3.13.1','Migration Hub','What is AWS Migration Hub?','<strong>AWS Migration Hub</strong> provides a central place to track application migration progress.','','','Track migration progress = Migration Hub.'],
['D3.13.2','DataSync','What is AWS DataSync?','<strong>AWS DataSync</strong> automates and accelerates online data transfer between on-premises storage and AWS storage services.','','','Online data transfer to AWS storage = DataSync.'],
['D4.1.1','Pay-As-You-Go','What is pay-as-you-go pricing?','<strong>Pay-as-you-go</strong> means paying for AWS services based on actual usage instead of buying infrastructure upfront.','','','Variable cost and no upfront hardware = pay-as-you-go.'],
['D4.2.1','EC2 Pricing Choice','How do you choose an EC2 pricing option?','Use <strong>On-Demand</strong> for flexibility, <strong>Reserved Instances</strong> or <strong>Savings Plans</strong> for predictable usage, <strong>Spot</strong> for interruptible workloads, and <strong>Dedicated Hosts</strong> for physical host needs.','','','This is heavily tested.'],
['D4.3.1','Cost Explorer vs Budgets','How are Cost Explorer and Budgets different?','<strong>Cost Explorer</strong> analyzes cost and usage trends. <strong>AWS Budgets</strong> alerts when cost or usage reaches thresholds.','','','Analyze = Cost Explorer. Alert = Budgets.'],
['D4.3.2','CUR','What is the AWS Cost and Usage Report?','The <strong>Cost and Usage Report</strong>, or <strong>CUR</strong>, provides the most detailed AWS billing and usage data.','','','Most detailed billing data = CUR.'],
['D4.5.1','Pricing Calculator','What is AWS Pricing Calculator?','<strong>AWS Pricing Calculator</strong> estimates AWS costs before you deploy or migrate workloads.','','','Estimate future costs = Pricing Calculator.'],
['D4.6.1','Support Plans','What support-plan facts are most tested?','<strong>Basic</strong> is free. <strong>Developer</strong> is the cheapest paid technical plan. <strong>Business</strong> adds 24/7 technical support and full Trusted Advisor. <strong>Enterprise</strong> adds a designated TAM and Concierge Support.','','Verify current prices and response times at AWS before booking.','Full Trusted Advisor = Business or higher. TAM = Enterprise.'],
['D4.7.1','Marketplace and APN','How are AWS Marketplace and APN different?','<strong>AWS Marketplace</strong> is for buying third-party software that runs on AWS. <strong>AWS Partner Network</strong> is AWS global network of consulting and technology partners.','','','Software catalog = Marketplace. Partners = APN.']
];
const cards=raw.map(x=>({id:x[0],topic:x[1],q:x[2],a:x[3],analogy:x[4],trap:x[5],tip:x[6],domain:x[0].slice(0,2)}));
const confusedPairs=[
['Security Group vs NACL',['Resource/instance-level','Stateful','Allow rules only','Return traffic automatically allowed'],['Subnet-level','Stateless','Allow and deny rules','Return traffic must be explicitly allowed']],
['S3 vs EBS',['Object storage','Buckets and objects','Files, backups, logs, static websites'],['Block storage','Volumes attached to EC2','Server disk']],
['EFS vs FSx',['Shared Linux file system','Elastic and serverless','Many EC2 instances can mount it'],['Managed specialized file systems','Windows, Lustre, ONTAP, OpenZFS','Specific file-system needs']],
['CloudWatch vs CloudTrail',['Metrics, logs, alarms, dashboards','How is it performing?','Operational monitoring'],['API activity audit','Who did what?','Governance and investigation']],
['RDS Multi-AZ vs Read Replica',['High availability','Automatic failover','Standby copy'],['Read scaling','Serves read traffic','Can reduce load on primary']],
['SNS vs SQS',['Pub/sub notifications','Push to subscribers','Fan-out pattern'],['Message queue','Consumers poll and process','Decoupling and buffering']],
['WAF vs Shield',['Filters web requests','Blocks SQL injection/XSS patterns','Layer 7 web protection'],['Protects against DDoS','Standard is free','Advanced adds response help']],
['KMS vs Secrets Manager',['Manages encryption keys','Used by many AWS services','Key rotation'],['Stores and rotates secrets','Database passwords/API keys','Credential retrieval']]
];
const state={index:0,filtered:[...cards],flipped:false,statuses:JSON.parse(localStorage.getItem('awsFlashcardStatus')||'{}')};
const $=id=>document.getElementById(id);
const els=['domainFilter','modeFilter','searchBox','deckTitle','cardCounter','flashcard','cardId','backCardId','cardDomain','cardTopic','backTopic','cardQuestion','cardAnswer','cardExtras','prevBtn','nextBtn','knownBtn','reviewBtn','shuffleBtn','resetBtn','masteryText','masteryBar','progressDetail','pairGrid'].reduce((a,id)=>(a[id]=$(id),a),{});
function init(){Object.entries(domains).forEach(([k,v])=>{const o=document.createElement('option');o.value=k;o.textContent=v;els.domainFilter.append(o)});renderPairs();bind();applyFilters();updateProgress()}
function bind(){els.domainFilter.onchange=applyFilters;els.modeFilter.onchange=applyFilters;els.searchBox.oninput=applyFilters;els.flashcard.onclick=flip;els.flashcard.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();flip()}};els.prevBtn.onclick=prev;els.nextBtn.onclick=next;els.knownBtn.onclick=()=>mark('known');els.reviewBtn.onclick=()=>mark('review');els.shuffleBtn.onclick=shuffle;els.resetBtn.onclick=resetProgress;document.onkeydown=e=>{if(e.target.matches('input,select'))return;if(e.key==='ArrowRight')next();if(e.key==='ArrowLeft')prev();if(e.key.toLowerCase()==='k')mark('known');if(e.key.toLowerCase()==='r')mark('review')}}
function applyFilters(){const d=els.domainFilter.value,m=els.modeFilter.value,t=els.searchBox.value.trim().toLowerCase();state.filtered=cards.filter(card=>{const s=state.statuses[card.id];const rapid=card.tip||card.trap||['D1.2.1','D1.4.1','D2.1.1','D3.5.2','D4.2.1'].includes(card.id);const hay=`${card.id} ${card.topic} ${card.q} ${card.a} ${card.analogy} ${card.trap} ${card.tip}`.toLowerCase();return(d==='all'||card.domain===d)&&(m==='all'||(m==='unseen'&&!s)||(m==='review'&&s==='review')||(m==='known'&&s==='known')||(m==='rapid'&&rapid))&&hay.includes(t)});state.index=0;state.flipped=false;els.flashcard.classList.remove('is-flipped');renderCard();renderTitle()}
function renderTitle(){const d=els.domainFilter.value==='all'?'All domains':domains[els.domainFilter.value];els.deckTitle.textContent=`${d} - ${els.modeFilter.options[els.modeFilter.selectedIndex].textContent}`}
function renderCard(){if(!state.filtered.length){els.cardId.textContent='No match';els.backCardId.textContent='No match';els.cardDomain.textContent='Adjust filters';els.cardTopic.textContent='No cards match this filter';els.backTopic.textContent='No cards match this filter';els.cardQuestion.textContent='Try another domain, mode, or search term.';els.cardAnswer.innerHTML='No matching <strong>flashcards</strong> are currently visible.';els.cardExtras.innerHTML='';els.cardCounter.textContent='0 / 0';return}const card=state.filtered[state.index];els.cardId.textContent=card.id;els.backCardId.textContent=card.id;els.cardDomain.textContent=domains[card.domain];els.cardTopic.textContent=card.topic;els.backTopic.textContent=card.topic;els.cardQuestion.textContent=card.q;els.cardAnswer.innerHTML=card.a;els.cardExtras.innerHTML=[card.analogy?`<div class="extra"><strong>Analogy:</strong> ${card.analogy}</div>`:'',card.trap?`<div class="extra trap"><strong>Trap:</strong> ${card.trap}</div>`:'',card.tip?`<div class="extra"><strong>Exam tip:</strong> ${card.tip}</div>`:''].join('');els.cardCounter.textContent=`${state.index+1} / ${state.filtered.length}`;els.knownBtn.textContent=state.statuses[card.id]==='known'?'Known (marked)':'Known';els.reviewBtn.textContent=state.statuses[card.id]==='review'?'Needs review (marked)':'Needs review'}
function flip(){if(!state.filtered.length)return;state.flipped=!state.flipped;els.flashcard.classList.toggle('is-flipped',state.flipped)}
function next(){if(!state.filtered.length)return;state.index=(state.index+1)%state.filtered.length;state.flipped=false;els.flashcard.classList.remove('is-flipped');renderCard()}
function prev(){if(!state.filtered.length)return;state.index=(state.index-1+state.filtered.length)%state.filtered.length;state.flipped=false;els.flashcard.classList.remove('is-flipped');renderCard()}
function mark(status){if(!state.filtered.length)return;state.statuses[state.filtered[state.index].id]=status;localStorage.setItem('awsFlashcardStatus',JSON.stringify(state.statuses));updateProgress();renderCard();next()}
function updateProgress(){const known=cards.filter(c=>state.statuses[c.id]==='known').length,review=cards.filter(c=>state.statuses[c.id]==='review').length,p=Math.round(known/cards.length*100);els.masteryText.textContent=`${p}%`;els.masteryBar.style.width=`${p}%`;els.progressDetail.textContent=`${known} known - ${review} need review - ${cards.length} total`}
function shuffle(){for(let i=state.filtered.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[state.filtered[i],state.filtered[j]]=[state.filtered[j],state.filtered[i]]}state.index=0;state.flipped=false;els.flashcard.classList.remove('is-flipped');renderCard()}
function resetProgress(){if(!confirm('Reset all known/review marks?'))return;state.statuses={};localStorage.removeItem('awsFlashcardStatus');updateProgress();applyFilters()}
function renderPairs(){els.pairGrid.innerHTML=confusedPairs.map(p=>`<article class="pair-card"><h3>${p[0]}</h3><table><thead><tr><th>First</th><th>Second</th></tr></thead><tbody>${p[1].map((l,i)=>`<tr><td>${l}</td><td>${p[2][i]||''}</td></tr>`).join('')}</tbody></table></article>`).join('')}
init();
